### PR TITLE
add gncdu

### PR DESCRIPTION
**Pull request by xgdgsc**

### CODE REVIEW

**Comment by DimitrisPa** [comment]
Project seems to be discontinued (**Last commit Mar 2020 and latest release Aug 2019**)

**Comment by xgdgsc** [comment]
I feel many Go tools could be like this, written once and works well, not many needs to update. More visibility through awesome lists would help those get alive.

**Comment by DimitrisPa** [comment]
True, but we try to keep the list with up to date software and also seems like a small project without many stars & open/closed issues, so i don't know if this is going to be a very good experience for a new user. But if you use it until this day and it works fine for you, i could reopen the PR.

**Comment by xgdgsc** [comment]
How about add stars like this https://github.com/luong-komorebi/Awesome-Linux-Software/commit/703287a3ce8743dc7d82b5237bd13cd4b11c6f70 and let user decide. Could also add formating like  https://github.com/p-ranav/awesome-hpp/blob/master/README.md#data-structures-and-algorithms

**Comment by DimitrisPa** [comment]
I like your idea, but i would like to hear @luong-komorebi's thoughts on this one.

**Pull request closed without merging**
