### PR TITLE
Added Mortar - Boot Security

### PR DESCRIPTION
**Pull request by noahbliss**
Added mortar, a tool to protect against system tampering.

### CODE REVIEW

**Comment by luong-komorebi** [comment]
I personally inspected the code as well as submitted to some of our dearest community. https://www.reddit.com/r/linuxadmin/comments/kq3evf/mortar_linuxnative_tpmbacked_bitlocker/ , https://www.reddit.com/r/linux/comments/kq3f3b/linuxnative_tpmbacked_bitlocker/ .
I personally love it and really want this to be a reality for all of us in the future, but right now it looks like it is in its early stage so I am gonna put a hang here and wait for some time. What s your opinion on this @noahbliss

**Comment by noahbliss** [comment]
@luong-komorebi sounds like a plan! Excited to see how the community responds. Maybe I'll even get a little help. :P

**Comment by noahbliss** [comment]
@luong-komorebi going to shamelessly bump this. Not to brag too hard but looks like I got stars on Mortar from people at Google, Microsoft, Yandex, and HP.

**Comment by luong-komorebi** [comment]
Love it when you succeed. Hope you have a great time with your project

**Comment by noahbliss** [comment]
Sweet, thank you much!

**Pull request merged**
