### PR TITLE
added few utilities

### PR DESCRIPTION
**Pull request by sumanth1591**
added [cava](https://github.com/karlstav/cava) for audio visualizations,[tealdeer](https://dbrgn.github.io/tealdeer/) a cached tldr,[airpaste](https://github.com/mafintosh/airpaste) for terminal file sharing and [lolcat](https://github.com/busyloop/lolcat) to display colorful text and [nushell](https://www.nushell.sh/)

### CODE REVIEW

**Comment by sumanth1591** [comment]
@luong-komorebi please review

**Review by DimitrisPa — COMMENTED** [review]
@sumanth1591 Can you please place the apps in alphabetical order instead of being at the end of each category (cava, nushell and airpaste)?

**Comment by sumanth1591** [comment]
> @sumanth1591 Can you please place the apps in alphabetical order instead of being at the end of each category (cava, nushell, airpaste and lolcat)?

Hi I sorted the apps,I should've read contributing.md or payed close attention to how everything was ordered, sorry

**Review by DimitrisPa — APPROVED** [review]
LGTM

**Pull request merged**
